### ISSUE TITLE
Icons disappear on hover D:

### ISSUE THREAD

**Issue by ongyongen** [gohyongjing/portfolio#1]
- github and linkedin icons disappeared on hover
- 'Yong Jing' word at the navbar disappeared on hover 
- attached a screenshot image to show what happens when i hovered over the Linkedin icon
<img height="300"  width="400" alt="Screenshot 2024-01-15 at 12 55 53 AM" src="https://github.com/gohyongjing/portfolio/assets/97529863/a5d44473-d1f0-47bd-bfc5-42ee55242ad2">

**Comment by gohyongjing** [comment]
Fixed in fa2fd7b4a734aa30935d9f8bb5f189cc53c3fb95 :)
